# Generated by Django 4.2.11 on 2024-04-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_rename_name_doctor_firstname_doctor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrator',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
