# Generated by Django 4.2.11 on 2024-04-04 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_administrator_email_administrator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic_app.administrator'),
        ),
    ]
