# Generated by Django 4.2.11 on 2024-04-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0004_alter_appointment_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='therapies',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='clinic_app.therapy'),
        ),
    ]
