# Generated by Django 4.2.11 on 2024-04-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_administrator_message_usermessage_delete_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(default=0, null=True),
        ),
    ]
